services:
  ollama:
    image: ollama/ollama:rocm
    restart: unless-stopped

    # Memory and CPU limits
    deploy:
      resources:
        limits:
          memory: 24G
          cpus: '6.0'
        reservations:
          memory: 16G
          cpus: '4.0'

    # AMD ROCm GPU devices
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri

    # Ports
    ports:
      - "11434:11434"

    # Volumes
    volumes:
      - ollama_data:/root/.ollama

    # Environment variables for performance optimization
    environment:
      - OLLAMA_NUM_PARALLEL=6
      - OMP_NUM_THREADS=6
      - OLLAMA_NUM_THREADS=8
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_HOST=0.0.0.0
      - ROCM_VISIBLE_DEVICES=all
      - HIP_VISIBLE_DEVICES=all
      - GOMAXPROCS=6

    # Health check
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Combined AgroTech Application (Frontend + Backend)
  agrotech-app:
    build:
      context: .
      dockerfile: env-deployment/Dockerfile
    restart: unless-stopped

    # CPU and memory limits
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2.0'
        reservations:
          memory: 768M
          cpus: '1.0'

    # Ports
    ports:
      - "3000:80"

    # Environment variables
    environment:
      - OLLAMA_URL=http://ollama:11434

    # Dependencies
    depends_on:
      ollama:
        condition: service_healthy

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# Named volumes
volumes:
  ollama_data:
    driver: local

# Networks
networks:
  default:
    driver: bridge
