name: 'Docker Build and Push'
description: 'Build Docker image and push to Docker Hub'
inputs:
  dockerhub-username:
    description: 'Docker Hub username'
    required: true
  dockerhub-token:
    description: 'Docker Hub access token'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: './server/Dockerfile'
  context-path:
    description: 'Build context path'
    required: false
    default: './server'
  push-latest:
    description: 'Push latest tag'
    required: false
    default: 'true'

outputs:
  image-digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  image-tags:
    description: 'Image tags'
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        shell: bash

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
        shell: bash

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.dockerhub-username }}/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
        shell: bash

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context-path }}
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        shell: bash
