name: Production Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      release_notes:
        description: 'Release notes (optional)'
        required: false
        type: string

jobs:
  create-tag-and-release:
    runs-on: ubuntu-22.04
    name: Create Git Tag and Docker Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push production Docker image
        id: docker-production
        uses: ./.github/actions/docker-push
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          image-name: agrotech-ai-app
          context-path: '.'
          dockerfile-path: 'env-deployment/Dockerfile'
          push-as-latest: 'true'
          tag-version: ${{ github.event.inputs.version }}

      - name: Post-release notification
        run: |
          echo "🎉 Production release ${{ github.event.inputs.version }} completed successfully!"
          echo "📦 Docker image: ${{ secrets.DOCKERHUB_USERNAME }}/agrotech-ai-app:${{ github.event.inputs.version }}"
          echo "🏷️  Git tag: ${{ github.event.inputs.version }}"
          echo "🚀 Both version tag and latest tag have been pushed to DockerHub"
